### ISSUE TITLE
Failing Cancellation Check

### ISSUE THREAD

**Issue by dahlbyk** [huboard/huboard-web#222]
New error introduced by #208:

> Message: undefined method `[]' for false:FalseClass
>
> Backtrace:
> 
> ```
> /app/lib/hu_board/account_helpers.rb:33 subscription_canceled?
> /app/lib/use_case/private_repo.rb:42 has_subscription?
> ```

https://github.com/huboard/huboard-web/blob/f0629ef4704d824d0715908cc938dc7b77d148b7/lib/hu_board/account_helpers.rb#L33
https://github.com/huboard/huboard-web/blob/master/lib/use_case/private_repo.rb#L42
